name: 🐛 Bug Report
description: Report a bug or issue with the Grayjay sources site
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happens
    validations:
      required: true
      
  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the site is affected?
      options:
        - Website/UI
        - Source Listing
        - Source Download
        - Search Functionality
        - Documentation
        - Other
    validations:
      required: true
      
  - type: input
    id: source-affected
    attributes:
      label: Affected Source (if applicable)
      description: If the bug is related to a specific source, please specify
      placeholder: e.g., YouTube Source v1.0.0
    validations:
      required: false
      
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: false
      
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., 118.0.5993.70
    validations:
      required: false
      
  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile
        - Tablet
    validations:
      required: false
      
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS Sonoma, Android 14
    validations:
      required: false
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Error Messages
      description: If applicable, paste any error messages or console logs
      placeholder: Paste error messages or console output here
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any other information that might be helpful
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our community guidelines
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
